### ISSUE TITLE
Theme Release milestone

### ISSUE THREAD

**Issue by mAKEkr** [mAKEkr/blog#6]
- list
  - [ ] pagination design
  - [ ] tag/category page design
  - [ ] tags/categories page design
- post
  - [ ] pager design
- common
  - [ ] english based environment typography
- [ ] make package and publish
- [ ] package test
